name: image_painter
description: A flutter package for drawing over images. Supports color,
  strokeWidth, different paintModes and exporting image.
version: 0.5.1+2
homepage: https://github.com/yellowQ-software/yellowQ-Flutter-Image-Painter

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file: ^6.1.4

dev_dependencies:
  flutter_lints: ^2.0.1
